### PR TITLE
support for additional attributes in User object

### PR DESCRIPTION
**Pull request by jglapa**
I think it would be really helpful to be able to attach more attributes to the User interface.

Implementation could be much nicer. We don't need the fields in the User class anymore but I didn't want to break any assumptions or existing tests.

If the change is accepted I can also rephrase the README.

### CODE REVIEW

**Comment by alfakini** [comment]
Thats good :) @jglapa please update the README and I will accept this PR.

**Comment by jglapa** [comment]
Hey @alfakini I updated the Readme. I hope it's sufficient.

PS.
Can we expect a plugin release any time soon?

**Comment by alfakini** [comment]
Sure, tonight I will release a new version with the fixes :)

**Comment by alfakini** [comment]
Hey @jglapa, this repository moved to https://github.com/agorapulse/grails-raven

**Comment by miere** [comment]
Massa quando a comunidade participa dos projetos neh? :D

**Pull request merged**
